Repository clue/reactphp-redis, pull requests merged in 2022-05, with the labels that each got.

#125 Fix code examples in documentation
  README.md
Labels: documentation

#126 Hello `3.x` development branch
  README.md
Labels: maintenance

#127 Update to require PHP 7.1+
  .github/workflows/ci.yml
  README.md
  composer.json
  examples/cli.php
  examples/publish.php
  examples/subscribe.php
  phpunit.xml.legacy
  src/Factory.php
  src/LazyClient.php
  src/StreamingClient.php
  tests/FactoryLazyClientTest.php
  tests/FactoryStreamingClientTest.php
  tests/FunctionalTest.php
  tests/LazyClientTest.php
  tests/StreamingClientTest.php
  tests/TestCase.php
Labels: maintenance, BC break

#128 Add type definitions for all APIs and tests
  README.md
  examples/incr.php
  examples/publish.php
  examples/subscribe.php
  src/Client.php
  src/Factory.php
  src/LazyClient.php
  src/StreamingClient.php
  tests/FactoryLazyClientTest.php
  tests/FactoryStreamingClientTest.php
  tests/FunctionalTest.php
  tests/LazyClientTest.php
  tests/StreamingClientTest.php
  tests/TestCase.php
Labels: new feature, BC break

#129 Simplify API, add new `RedisClient` and remove `Factory`
  README.md
  examples/cli.php
  examples/incr.php
  examples/publish.php
  examples/subscribe.php
  src/Client.php
  src/Io/Factory.php
  src/Io/StreamingClient.php
  src/RedisClient.php
  tests/FactoryLazyClientTest.php
  tests/FunctionalTest.php
  tests/Io/FactoryStreamingClientTest.php
  tests/Io/StreamingClientTest.php
  tests/RedisClientTest.php
Labels: new feature, BC break

#130 Reduce default idle time to 1ms
  README.md
  examples/incr.php
  examples/publish.php
  src/RedisClient.php
  tests/FunctionalTest.php
  tests/RedisClientTest.php
Labels: new feature, easy pick
